baseurl = "http://www.hcbravo.org/dscert-mldm"
languageCode = "en-us"
title = "CMSC643: Machine Learning and Data Mining"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "HÃ©ctor Corrada Bravo"
	description = "Machine Learning and Data Mining course. Part of the Department of Computer Science of the University of Maryland's Graduate Certificate in Data Science"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/hcorrada/dscert-mldm.git"

	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "blue"

 [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"

 [params.links]
      elms   = ""
      piazza = ""
[social]
	twitter = "hcorrada"
	github  = "hcorrada"

[[menu.main]]
  name = "Calendar"
  url  = "calendar/"
  weight = 5

[[menu.main]]
	name   = "Logistics"
	url    = "logistics/"
	weight = 10

[[menu.main]]
	name   = "Resources"
	url    = "resources/"
	weight = 30

[[menu.main]]
	name   = "Projects"
	url    = "projects/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
